// Generated by CoffeeScript 1.6.3
(function() {
  var $;

  $ = jQuery;

  $(function() {
    var i, j, _i, _j;
    for (i = _i = 0; _i < 3; i = ++_i) {
      ($("#gridTable>tbody")).append("<tr>");
      for (j = _j = 0; _j < 3; j = ++_j) {
        ($("#gridTable>tbody")).append("<td><div class=\"gridCell\"></div></td>");
      }
      ($("#gridTable>tbody")).append("</tr>");
      ($(".gridCell")).droppable({
        hoverClass: "drop-hover",
        drop: (function(ev, ui) {
          ui.draggable.parent().removeClass("filled");
          ui.draggable.detach();
          console.log(($(this)).offset());
          ui.draggable.appendTo($(this));
          ui.draggable.offset(($(this)).offset());
          return ($(this)).addClass("filled");
        })
      });
    }
    ($(".logicBox")).draggable({});
    console.log($(".logicBox").draggable("option", "zIndex"));
    ($(".logicBox")).on("drag", (function() {
      return console.log($(this).x);
    }));
    return ($(".logicBoxArrow")).draggable({
      drag: (function(ev, ui) {
        console.log(ev.clientX);
        return ($(this)).clientX = 0;
      })
    });
  });

}).call(this);
